# Create a program that will play the “cows and bulls” game with the user. The game works like this:

# Randomly generate a 4-digit number. Ask the user to guess a 4-digit number. For every digit that the user guessed correctly in the correct place, they have a “cow”. For every digit the user guessed correctly in the wrong place is a “bull.” Every time the user makes a guess, tell them how many “cows” and “bulls” they have. Once the user guesses the correct number, the game is over. Keep track of the number of guesses the user makes throughout the game and tell the user at the end.

# Say the number generated by the computer is 1038. An example interaction could look like this:

#   Welcome to the Cows and Bulls Game! 
#   Enter a number: 
#   >>> 1234
#   2 cows, 0 bulls
#   >>> 1256
#   1 cow, 1 bull
#   ...

# Until the user guesses the number.

import random

number = random.choices(range(0, 10), k=4)
tries = 0

def get_input():
    player_guess = int(input("Guess a four-digit number: "))
    player_list = [int(x) for x in str(player_guess)]
    return player_list

def cows_bulls(player_list):
    global tries
    tries += 1
    cows = 0
    bulls = 0
    for item in range(len(player_list)):
        if player_list[item] == number[item]:
            cows += 1
        if player_list[item] in number:
            bulls += 1
    bulls = bulls - cows
    if cows == 4:
        win()
        return
    
    print(cows)
    print(bulls)

def win():
    if tries == 1:
        print("You win! It only took you " + str(tries) + " try! Are you a wizard?")    
    else:
        print("You win! It only took you " + str(tries) + " tries!")


print(number)
cows_bulls(get_input())